trigger:
  branches:
    include:
      - main

variables:
- template: templates/variables.yml

stages:
- stage: Build
  displayName: Build
  jobs:
  - template: templates/build.yml
    parameters:
      imageName: '$(Build.Repository.Name)-compiler:$(Build.BuildId)'

- stage: SAST
  displayName: Static Analysis
  dependsOn: Build
  jobs:
  - template: templates/sast.yml

- stage: Release
  jobs:
  - template: templates/release.yml
    parameters:
      artifactName: demo
      version: $(Build.BuildId)

- stage: Deploy
  displayName: Deploy
  dependsOn: Release
  jobs:
    - template: templates/deploy.yml
      parameters:
        remoteHost: $(RemoteHost)
        remoteUser: $(RemoteUser)
        remotePath: $(RemotePath)
        backupPath: $(BackupPath)
        healthCheckUrl: $(HealthCheckUrl)
