parameters:
  imageName: ''

jobs:
- job: Build
  displayName: Build
  pool:
    name: Default
  steps:
    - powershell: |
        Write-Host "Building Docker image..."
        docker build --target builder -t ${{ parameters.imageName }} .
        Write-Host "Extracting JAR..."
        $container = docker create ${{ parameters.imageName }}
        docker cp "$container:/app/target/*.jar" "$(Build.ArtifactStagingDirectory)"
        docker rm $container
      displayName: 'Build & Extract JAR'

