parameters:
- name: artifactName
  type: string
  default: ''
- name: version
  type: string
  default: ''

jobs:
- job: Release
  displayName: Publish Artifact
  pool:
    name: Default

  steps:
  - task: PublishPipelineArtifact@1
    displayName: 'Publish JAR as Pipeline Artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: ${{ parameters.artifactName }}
