parameters:
  artifactName: ''
  version: ''

jobs:
- job: Release
  displayName: Publish Artifact
  pool:
    name: Default
  steps:
    - task: AzureCLI@2
      displayName: 'Publish Artifact to Azure Artifacts'
      inputs:
        azureSubscription: 'MiServiceConnection'  
        scriptType: 'pscore'
#        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Publishing artifact to Azure Artifacts..."
          az artifacts universal publish \
            --organization $(System.TeamFoundationCollectionUri) \
            --project $(System.TeamProject) \
            --feed $(FeedName) \
            --name ${{ parameters.artifactName }} \
            --version ${{ parameters.version }} \
            --path $(Build.ArtifactStagingDirectory)